Fix -Wparentheses warning not ignored on NVCC
boostorg/mpl pull request #62
Opened 2022-03-10 20:21 UTC by aladram

BOOST_GCC is not defined for NVCC, therefore we should use BOOST_GCC_VERSION.

2022-03-10 22:46 UTC, aladram commented
@mclow could you please look at the Windows CI results? Failure seems to come from a package missing from the msys repo (pacman 5.2.1-12). This change only affects GCC + NVCC. Thanks!

2022-03-18 16:38 UTC, aladram commented
@eldiener any chance you could look at this PR when you have some time? Thanks!

2022-05-01 11:36 UTC, jeking3 commented
CI failure is known and tracked by #50

2022-05-01 11:49 UTC, jeking3 requested changes
I would suggest that https://github.com/boostorg/mpl/pull/34 should have used BOOST_WORKAROUND based on work done 5 years prior to standardize on that macro, so this is a good opportunity to do the same and remedy that.  I will push a fix.

2022-05-01 11:49 UTC, jeking3 commented on include/boost/mpl/assert.hpp
> +#if defined(BOOST_GCC_VERSION) && BOOST_GCC_VERSION >= 80000
```suggestion
#if BOOST_WORKAROUND(BOOST_GCC_VERSION, >= 80000)
```

2022-05-01 11:54 UTC, jeking3 approved these changes

2022-05-01 12:47 UTC, merged